// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeEg6DrXqqTogXs5AJVPcZkzAiPeB68ek',
    appId: '1:685258257596:web:7b03104d09121893a08cb9',
    messagingSenderId: '685258257596',
    projectId: 'the-greatest-mensa-app-ever',
    authDomain: 'the-greatest-mensa-app-ever.firebaseapp.com',
    storageBucket: 'the-greatest-mensa-app-ever.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQR_N1V5_ejqEM-xUfB0lJcwWojVQXcB8',
    appId: '1:685258257596:android:3ed7c4fb1028c6e9a08cb9',
    messagingSenderId: '685258257596',
    projectId: 'the-greatest-mensa-app-ever',
    storageBucket: 'the-greatest-mensa-app-ever.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_zCKx4PkfZldKs3vuMk1Zd-sLUGNBw1A',
    appId: '1:685258257596:ios:7258aeeb04c1bfdaa08cb9',
    messagingSenderId: '685258257596',
    projectId: 'the-greatest-mensa-app-ever',
    storageBucket: 'the-greatest-mensa-app-ever.appspot.com',
    iosClientId: '685258257596-uofsk4ekdvt5a56nq0d6miamuvt46k1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.greatestMensaAppEverXxl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_zCKx4PkfZldKs3vuMk1Zd-sLUGNBw1A',
    appId: '1:685258257596:ios:7258aeeb04c1bfdaa08cb9',
    messagingSenderId: '685258257596',
    projectId: 'the-greatest-mensa-app-ever',
    storageBucket: 'the-greatest-mensa-app-ever.appspot.com',
    iosClientId: '685258257596-uofsk4ekdvt5a56nq0d6miamuvt46k1j.apps.googleusercontent.com',
    iosBundleId: 'com.example.greatestMensaAppEverXxl',
  );
}
